all:
  hosts:
    usagi:
      ansible_host: usagissh.skypattern.jp
      ansible_user: kaylee
      ansible_ssh_private_key_file: ~/.ssh/usagi
      ansible_ssh_common_args: '-o ProxyCommand="cloudflared access ssh --hostname %h"'

#monitoring:
#  hosts:
#    micro2:
#      ansible_host: micro2.skypattern.jp
#      ansible_user: ubuntu
#      ansible_ssh_private_key_file: ~/.ssh/micro2.key
